[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
gas_reports = ["Router"]
evm_version = "cancun"
solc = "0.8.25"
fs_permissions = [{ access = "read", path = "./out" }]
viaIR = true

[rpc_endpoints]
beratest = "https://artio.rpc.berachain.com/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
