[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
gas_reports = ["Router"]
evm_version = "cancun"
solc = "0.8.26"
fs_permissions = [{ access = "read", path = "./out" }]
viaIR = true

[rpc_endpoints]
sepolia = "https://alpha-fittest-energy.ethereum-sepolia.quiknode.pro/ad2fa26d4fdae56c65fded4c4b8eadc7bd06778b/"
mainnet = "https://greatest-icy-rain.quiknode.pro/39f79e4968518a7d0519a3638f730848fc4663c2/"
